version: 0.2

phases:
  install:
    commands:
      - echo "==== Installing dependencies (if any) ===="
  pre_build:
    commands:
      - echo "==== Pre-build phase started ===="
      - mkdir -p build
  build:
    commands:
      - echo "==== Build phase started ===="
      - |
        cat <<EOF > build/index.html
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>About Page</title>
          <style>
            body {
              font-family: Arial, sans-serif;
              background-color: #f0f0f0;
              margin: 0;
              padding: 0;
              text-align: center;
            }
            .container {
              margin-top: 100px;
            }
            h1 {
              color: #2c3e50;
            }
            p {
              font-size: 18px;
              color: #555;
              margin: 10px 0;
            }
          </style>
        </head>
        <body>
          <div class="container">
            <h1>About This Website</h1>
            <p>This static site is deployed using AWS CodePipeline, CodeBuild, and S3.</p>
            <p>Created by Himanshu Nimje 🚀</p>
            <p>Build time: $(date)</p>
          </div>
        </body>
        </html>
        EOF
  post_build:
    commands:
      - echo "==== Build complete. Files are ready to deploy. ===="

artifacts:
  files:
    - '**/*'
  base-directory: build
