version: 0.2

phases:
  install:
    commands:
      - echo Installing...
  build:
    commands:
      - echo Building site...
artifacts:
  files:
    - '*/'
  base-directory: .
  discard-paths: no

post_build:
  commands:
    - echo Deploying to S3...
    - aws s3 cp . s3://himanshucicd-bucket/ --recursive
